# JPA
spring:
  jpa:
  properties:
  hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  ddl-auto: update
  # MySql
  datasource:
    url: jdbc:mysql://localhost:3306/siget?useSSL=false&serverTimezone=UTC
    username: root
    #password: root
    password : 2$TCxQb*GDAy
    # Connection Pool
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true

server:
  port: 80
  servlet:
    context-path: /siget




