# JPA
spring:
  jpa:
  properties:
  hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  ddl-auto: update
  # MySql
  datasource:
#    url: jdbc:mysql://localhost:3306/siget?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://192.168.100.15:3306/siget?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: invitado
    password: invitado
    #password : 2$TCxQb*GDAy
    # Connection Pool
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: alexagander717@gmail.com
    password: wdqabawkftymgdaw
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

server:
  port: 80
  servlet:
    context-path: /siget




